version: '3.9'
services:
  master:
    image: locustio/locust
    command: -f /scripts/locustfile.py --master
    ports:
      - "8089:8089"
      - "5557:5557"
      - "5558:5558"
    volumes:
      - ./script:/script

  slave:
    image: locustio/locust
    command: -f /scripts/locustfile.py --worker --master-host=localhost
    network_mode: host
    depends_on:
      - master
    volumes:
      - ./script:/script